
/**
 * \file io_nchilada_header.c
 *
 * Provides functions for reading and writing the header of NCHILADA
 * files.
 */

/*** TODO:  
combine reads from nbodies of gas,dark,stars to ngas,ndark,nstar,nbodies_total
     by adding the variables to the dummy (header) struct
***/


/**********************************************************************\
 *    Includes                                                        * 
 \**********************************************************************/
#include <stdio.h>
#include <stdlib.h>
#include <limits.h>
#include <stdint.h>

#include "io_nchilada_header.h"
#include "io_util.h"


/**********************************************************************\
 *    Local defines, structure definitions and typedefs               * 
 \**********************************************************************/
#define SKIP(f) {fseek(f, 4L, SEEK_CUR);}


/**********************************************************************\
 *    Prototypes of local functions                                   * 
 \**********************************************************************/


/**********************************************************************\
 *    Implementation of global functions                              * 
 \**********************************************************************/
extern io_nchilada_header_t
io_nchilada_header_get(io_logging_t log, io_nchilada_file_t f)
{
  io_nchilada_header_t dummy;
  long skipsize;
  int iloop;
  FILE *fnchilada;
  char nchiladaline[2048];
  
  /* Some sanity checks */
  if ((f == NULL) || (f->file == NULL))
    return NULL;
  
  /* Check if there already is a header, do nothing then */
  if (f->header != NULL)
    return f->header;
  
  /* Create the header structure array */
  dummy = (io_nchilada_header_t)malloc((size_t)sizeof(io_nchilada_header_struct_t));
  if (dummy == NULL) {
    io_logging_memfatal(log, "NCHILADA header structure");
    return NULL;
  }
  
  /* just to be on the safe side: rewind the file to the start... */
  rewind(f->file);
  
  /* Now start reading the header */
  io_util_readuint32(f->file, &(dummy->magic), f->swapped);
  io_util_readdouble(f->file, &(dummy->time), f->swapped);
  io_util_readuint32(f->file, &(dummy->iHighWord), f->swapped);
  io_util_readuint32(f->file, &(dummy->nbodies), f->swapped);
  io_util_readuint32(f->file, &(dummy->ndim), f->swapped);
  io_util_readuint32(f->file, &(dummy->code), f->swapped);

  fprintf(stderr,"magic    = %"PRIu32"\n",dummy->magic);
  fprintf(stderr,"time = %lf\n",dummy->time);
  fprintf(stderr,"iHighWord    = %"PRIu32"\n",dummy->iHighWord);
  fprintf(stderr,"nbodies    = %"PRIu32"\n",dummy->nbodies);
  fprintf(stderr,"ndim  = %"PRIu32"\n",dummy->ndim);
  fprintf(stderr,"code   = %"PRIu32"\n",dummy->code);
//  exit(0);
  
/////////// TODO  tipsy.info is generated by ahf.  Using tipsy.info also for nchilada format.
  /* read NCHILADA relevant (unit) information from an extra user provided file */
  if((fnchilada = fopen("tipsy.info","r")) == NULL)
    {
      io_logging_fatal(log,"Could not open nchilada.info containing the following information:");
      io_logging_fatal(log,"0.3                     NCHILADA_OMEGA0");
      io_logging_fatal(log,"0.7                     NCHILADA_LAMBDA0");
      io_logging_fatal(log,"20.0                    NCHILADA_BOXSIZE           [Mpc/h]");
      io_logging_fatal(log,"690.988298942671        NCHILADA_VUNIT             [km/sec]");
      io_logging_fatal(log,"2.2197e15               NCHILADA_MUNIT             [Msun/h]");
      io_logging_fatal(log,"2.2197e15               NCHILADA_EUNIT             [(km/sec)^2]");
      io_logging_fatal(log,"Please generate this file. Aborting now!");
      free(dummy);
      return NULL;
      //exit(0);
    }
  fgets(nchiladaline, 2048, fnchilada);
  sscanf(nchiladaline,"%lf",&(dummy->omega0));
  fgets(nchiladaline, 2048, fnchilada);
  sscanf(nchiladaline,"%lf",&(dummy->lambda0));
  fgets(nchiladaline, 2048, fnchilada);
  sscanf(nchiladaline,"%lf",&(dummy->boxsize));
  fgets(nchiladaline, 2048, fnchilada);
  sscanf(nchiladaline,"%lf",&(dummy->vunit));
  fgets(nchiladaline, 2048, fnchilada);
  sscanf(nchiladaline,"%lf",&(dummy->munit));  
  fgets(nchiladaline, 2048, fnchilada);
  sscanf(nchiladaline,"%lf",&(dummy->eunit));  
  fclose(fnchilada);

  io_logging_msg(log, INT32_C(5),"   nchilada.info -> omega0:                         %e",dummy->omega0);
  io_logging_msg(log, INT32_C(5),"   nchilada.info -> lambda0:                        %e",dummy->lambda0);
  io_logging_msg(log, INT32_C(5),"   nchilada.info -> boxsize:                        %e",dummy->boxsize);
  io_logging_msg(log, INT32_C(5),"   nchilada.info -> vunit:                          %e",dummy->vunit);
  io_logging_msg(log, INT32_C(5),"   nchilada.info -> munit:                          %e",dummy->munit);
  io_logging_msg(log, INT32_C(5),"   nchilada.info -> eunit:                          %e",dummy->eunit);
  
  
  f->header = dummy;

  return dummy;
}

extern void
io_nchilada_header_del(io_logging_t log, io_nchilada_header_t *header)
{
  if ( (header == NULL) || (*header == NULL) )
    return;
  
  free(*header);
  
  *header = NULL;
  
  return;
}

extern void
io_nchilada_header_write(io_logging_t log,
                      io_nchilada_header_t header,
                      io_nchilada_file_t f)
{
  if ( (header == NULL) || (f == NULL))
    return;
  
  if (f->mode != IO_FILE_WRITE)
    return;
  
  if (f->file == NULL)
    return;
  
  if (header != f->header) {
    io_logging_msg(log, INT32_C(1),
                   "Writing a different header than stored in "
                   "the file object to the file.");
  }
  
  /* TODO: Write the header */
  
  return;
}


extern void
io_nchilada_header_log(io_logging_t log, io_nchilada_header_t header)
{
  io_logging_msg(log, INT32_C(5), "   magic:                         %", PRIu32, header->magic);
  io_logging_msg(log, INT32_C(5), "  time:                       %e", header->time);
  io_logging_msg(log, INT32_C(5), "  iHighWord:                          %" PRIu32, header->iHighWord);
  io_logging_msg(log, INT32_C(5), "  nbodies:                          %" PRIu32, header->nbodies);
  io_logging_msg(log, INT32_C(5), "  ndim:                         %" PRIu32, header->ndim);
  io_logging_msg(log, INT32_C(5), "  code:                         %" PRIu32, header->code);
  return;
}


/**********************************************************************\
 *    Implementation of local functions                               * 
 \**********************************************************************/
